name: update-sitemap

on:
  schedule:
    # 日本時間の 0時に定期実行
    - cron: '0 15 * * *'

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Ping to Google
        run: |
          curl -X GET "http://www.google.com/ping?sitemap=https://ji23-dev.com//sitemap.xml"
